# Generated by Django 5.2 on 2026-09-16 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('autocuidado', 'Autocuidado'), ('taller_salud_mental', 'Taller de salud mental'), ('psicoterapia_individual', 'Psicoterapia individual'), ('escuela_buen_trato', 'Escuela del buen trato')], max_length=30, verbose_name='Tipo de actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('publico_objetivo', models.CharField(max_length=150, verbose_name='Público objetivo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('lugar_modalidad', models.CharField(max_length=150, verbose_name='Lugar o modalidad')),
                ('cupos', models.PositiveIntegerField(verbose_name='Cupos totales')),
                ('fecha_cierre_inscripciones', models.DateField(verbose_name='Fecha de cierre de inscripciones')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades')),
                ('tipo_retribucion', models.CharField(choices=[('gratis', 'Gratis'), ('pago', 'Pago'), ('donacion', 'Donación')], default='gratis', max_length=15, verbose_name='Tipo de retribución')),
                ('valor', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Valor (si es pago o sugerencia de donación)')),
                ('activa', models.BooleanField(default=True, verbose_name='Publicada')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('lista_espera', 'Lista de espera'), ('cancelada', 'Cancelada')], default='confirmada', max_length=15)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='actividades.actividad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='reservas.cliente')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
                'unique_together': {('actividad', 'cliente')},
            },
        ),
    ]
