# Generated by Django 5.2 on 2026-09-17 19:45

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validar_tamano_imagen]),
        ),
    ]
