# Generated by Django 5.2 on 2026-09-17 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_actividad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (si es pago o sugerencia de donación)'),
        ),
    ]
