# Generated by Django 5.2 on 2026-09-16 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio / sesión'), ('producto_fisico', 'Producto físico')], default='servicio', max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('activo', models.BooleanField(default=False, help_text='Se mantiene en False hasta activar venta de productos (Fase 5).', verbose_name='Activo para venta')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('manual', 'Coordinado manualmente'), ('webpay', 'Webpay'), ('mercadopago', 'Mercado Pago'), ('transferencia', 'Transferencia')], default='manual', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('fallido', 'Fallido')], default='pendiente', max_length=15)),
                ('referencia_externa', models.CharField(blank=True, help_text='ID de transacción de la pasarela de pago, cuando se integre.', max_length=100)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='actividades.inscripcion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='catalogo.producto')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'ordering': ['-creada_en'],
            },
        ),
    ]
