# Generated by Django 4.1 on 2024-07-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nuevos_recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomM', models.CharField(max_length=80, verbose_name='Nombre de Material')),
                ('image', models.ImageField(upload_to='projects')),
                ('desM', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
