# Generated by Django 4.1 on 2024-07-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevos_recursos',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
