# Generated by Django 4.1 on 2024-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0002_nuevos_recursos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevos_recursos',
            name='file',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nuevos_recursos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
