# Generated by Django 4.1 on 2024-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0003_nuevos_recursos_file_alter_nuevos_recursos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevos_recursos',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Archivo'),
        ),
    ]
