# Generated by Django 4.1 on 2024-09-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0004_alter_nuevos_recursos_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuevos_recursos',
            options={},
        ),
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomA', models.CharField(max_length=15, verbose_name='Nombre de Archivo')),
                ('desA', models.TextField(verbose_name='Descripción Archivo')),
                ('file_upload', models.FileField(upload_to='files', verbose_name='archivo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='nuevos_recursos.nuevos_recursos', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
    ]
