# Generated by Django 4.1 on 2024-09-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0005_alter_nuevos_recursos_options_archivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='nuevos_recursos',
            options={'verbose_name': 'nuevos_recurso', 'verbose_name_plural': 'nuevos_recursos'},
        ),
        migrations.RemoveField(
            model_name='nuevos_recursos',
            name='file',
        ),
    ]
