# Generated by Django 4.1 on 2024-09-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0006_alter_archivos_options_alter_nuevos_recursos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='nomA',
            field=models.CharField(max_length=60, verbose_name='Nombre de Archivo'),
        ),
    ]
