# Generated by Django 4.1 on 2024-09-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0007_alter_archivos_noma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevos_recursos',
            name='desM',
        ),
    ]
