# Generated by Django 5.2 on 2026-09-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0008_remove_nuevos_recursos_desm'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevos_recursos',
            name='desM',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
