# Generated by Django 5.2 on 2026-09-17 19:45

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevos_recursos', '0009_nuevos_recursos_desm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='file_upload',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.validators.validar_tamano_pdf], verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='nuevos_recursos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validar_tamano_imagen]),
        ),
    ]
