# Generated by Django 5.2 on 2026-09-16 03:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha bloqueada')),
                ('motivo', models.CharField(blank=True, max_length=120, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'bloqueo de fecha',
                'verbose_name_plural': 'bloqueos de fecha',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('convenio', models.CharField(choices=[('particular', 'Particular'), ('fonasa', 'Fonasa'), ('isapre', 'Isapre'), ('seguro', 'Seguro')], default='particular', help_text='Campo informativo, sin validación con la aseguradora (RF-A-06).', max_length=20, verbose_name='Convenio')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sesion', models.CharField(choices=[('psicoterapia_individual', 'Psicoterapia individual (60 min)'), ('taller_grupal', 'Taller grupal (180 min)'), ('autocuidado', 'Autocuidado (duración a convenir)')], max_length=30, verbose_name='Tipo de sesión')),
                ('modalidad', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=15, verbose_name='Modalidad')),
                ('fecha', models.DateField(verbose_name='Fecha solicitada')),
                ('hora', models.TimeField(verbose_name='Hora solicitada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
