# Generated by Django 5.2 on 2026-09-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pago_coordinado',
            field=models.BooleanField(default=False, help_text='Marcar cuando ya se coordinó el pago con el cliente (transferencia, link, efectivo, etc.). El MVP no tiene pasarela de pago: esto es solo un registro manual de Fabiola.', verbose_name='Pago coordinado'),
        ),
    ]
