# Generated by Django 5.2 on 2026-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_pago_coordinado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tipo_sesion',
            field=models.CharField(choices=[('psicoterapia_individual', 'Psicoterapia individual (60 min)'), ('taller_grupal', 'Taller grupal (180 min)'), ('autocuidado', 'Autocuidado para equipos (duración a convenir)')], max_length=30, verbose_name='Tipo de sesión'),
        ),
    ]
