# Generated by Django 4.1 on 2024-09-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocuidados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='autocuidados',
        ),
    ]
