# Generated by Django 4.1 on 2024-09-03 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autocuidados', '0002_rename_cursos_autocuidados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autocuidados',
            options={'verbose_name': 'autocuidado', 'verbose_name_plural': 'autocuidados'},
        ),
        migrations.RenameField(
            model_name='autocuidados',
            old_name='desC',
            new_name='desA',
        ),
        migrations.RemoveField(
            model_name='autocuidados',
            name='durC',
        ),
        migrations.RemoveField(
            model_name='autocuidados',
            name='idC',
        ),
        migrations.RemoveField(
            model_name='autocuidados',
            name='modC',
        ),
        migrations.RemoveField(
            model_name='autocuidados',
            name='nomC',
        ),
        migrations.RemoveField(
            model_name='autocuidados',
            name='valorC',
        ),
        migrations.AddField(
            model_name='autocuidados',
            name='clienteA',
            field=models.CharField(default='Valor por defecto', max_length=80, verbose_name='cliente autocuidado'),
        ),
        migrations.AddField(
            model_name='autocuidados',
            name='fechaA',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='autocuidados',
            name='id_a',
            field=models.AutoField(default='1', primary_key=True, serialize=False, verbose_name='ID autocuidado'),
        ),
        migrations.AddField(
            model_name='autocuidados',
            name='lugarA',
            field=models.CharField(default='sin asignar', max_length=20, verbose_name='Lugar autocuidado'),
        ),
    ]
