# Generated by Django 4.1 on 2024-09-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocuidados', '0004_alter_autocuidados_id_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocuidados',
            name='clienteA',
            field=models.CharField(default='sin asignar', max_length=80, verbose_name='cliente autocuidado'),
        ),
    ]
