# Generated by Django 4.1 on 2024-09-03 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocuidados', '0005_alter_autocuidados_clientea'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('autocuidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='autocuidados.autocuidados', verbose_name='autocuidado')),
            ],
        ),
    ]
