# Generated by Django 5.2 on 2026-09-17 19:45

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocuidados', '0008_alter_galeria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocuidados',
            name='image',
            field=models.ImageField(upload_to='projects', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='image',
            field=models.ImageField(upload_to='autocuidados', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validar_tamano_imagen]),
        ),
    ]
